fancybox: true ## If you want to use fancybox please set the value to true.
# disqus: hiberabyss ## Your disqus_shortname, e.g. username

gitment:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: hiberabyss
  repo: BlogComments
  client_id: 1d8f8c20107ae25974a9
  client_secret: 51011f6d751dd26667d56df8aa0d1c2e5e8847ab

gitalk:
  enable: true ## If you want to use Gitment comment system please set the value to true.
  owner: hiberabyss ## Your GitHub ID, e.g. username
  repo: BlogComments ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: 1d8f8c20107ae25974a9 ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: 51011f6d751dd26667d56df8aa0d1c2e5e8847ab ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin: ['hiberabyss']

uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## You changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b

# https://valine.js.org
valine:
  enable: false ## if you want to use Valine comment system, please set the value to true
  appid: GBcBBf3jExLmb3JSMt2K3mYn-gzGzoHsz ## your leancloud application appid
  appkey: fzAS8oS7VtSLRUVVKOviv671 ## your leancloud application appkey
  notify: true ## mail notifier , https://github.com/xCss/Valine/wiki
  verify: true ## Verification code
  placeholder: Just go go ## comment input placeholder text 
  avatar: 'wavatar' ## header image https://github.com/xCss/Valine/wiki
  pageSize: 10 ## 
  guest_info: nick,mail

google_search: true ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-93704704-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 5f9e6d84d1bec152fecef2cd2cfb7e4c ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: false ## If you want to use the share button please set the value to true, you must have hexo-helper-qrcode installed.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
total_visit_busuanzi: true
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"
donate:
  enable: true ## If you want to show the donate button after each post, please set the value to true and fill the following items according to your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: /img/AliPayQR.jpg
  wechat_qr: /img/WeChatQR.jpg
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://paypal.me/tufu9441

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss
  - page: Slides
    directory: slides/publish
    icon: fa-slideshare

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

  # - qrcode

qrcode: /img/AliRedPacket.jpeg

highlight:
  enable: false
  auto_detect: true
  line_number: false
  tab_replace: 

links:
  - title: Coolshell
    url: http://coolshell.cn
  - title: Curtisai
    url: https://curtisai.github.io

timeline:
  - num: 1
    word: 2014/06/12-Start

# Static files
js: js
css: css

# Theme version
version: 0.0.0
